version: '3.1'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: clustered_data_warehouse
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
